# Generated by Django 3.0.7 on 2020-06-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_header', models.CharField(max_length=100)),
                ('task_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_type', models.CharField(choices=[('Встреча', 'Встреча'), ('Звонок', 'Звонок')], max_length=30)),
                ('task_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
