# Generated by Django 3.0.7 on 2020-06-26 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_header', models.CharField(max_length=100)),
                ('task_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_type', models.CharField(choices=[('Встреча', 'Встреча'), ('Звонок', 'Звонок')], max_length=30)),
                ('task_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
