# Generated by Django 3.0.7 on 2020-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200627_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_header',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Звонок', 'Звонок')], max_length=30, verbose_name='Тип события'),
        ),
    ]
