# Generated by Django 3.0.7 on 2020-06-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200630_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celerytask',
            old_name='task',
            new_name='corresp_task',
        ),
    ]
