# Generated by Django 3.0.7 on 2020-06-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200701_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='corresp_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celery_task', to='tasks.Task'),
        ),
    ]
